#' Plotting the transition proabilities gamma for a fitted multilevel HMM
#'
#' \code{plot.mHMM_gamma} plots the tranisitoin probability matrix for a fitted
#' multilevel hidden markov model, by means of an alluvial plot (also known as
#' sankey diagram or riverplot) using the R package \code{alluvial}. The plotted
#' transition probability matrix either represents the probabilities at the
#' group level, i.e., representing the average transition probability matrix
#' over all subjects, or at the subject level. In case of the latter, the user
#' has to specify for which subject the transition probability matrix should be
#' plotted.
#'
#' @param x An object of class \code{mHMM_gamma}, generated by the function
#'   \code{\link{obtain_gamma}}.
#' @param subj_nr An integer specifying for which specific subject the
#'   transition probability matrix should be plotted. Only required if the input
#'   object represents the subject specific transition probability matrices.
#' @param cex numeric, scaling of fonts of category labels. When not specified,
#' defaults to \code{cex = 0.8}.
#' @param col vector of colors of the stripes.
#' @param hide logical, should particlular stripe be plotted. When not
#' specified, omits the lines representing a value of exactly zero.
#' @param ... Arguments to be passed to alluvial (see \code{\link[alluvial]{alluvial}})
#'
#' @return \code{plot.mHMM_gamma} returns a plot of the transition probability
#'   matrix. Depending on whether the input object represents the transiton
#'   probabilities at the group level or the subject specific transition
#'   probability matrices, the returned plot represents either the group
#'   transition probality matrix, or the transition probability matrix for a
#'   given subject, specified by \code{subject_nr}.
#'
#' @seealso \code{\link{mHMM_mnl}} for fitting the multilevel hidden Markov
#'   model, creating the object \code{mHMM}, and \code{\link{obtain_gamma}} to
#'   obtain the the transition proabilities gamma for a fitted multilevel HMM,
#'   creating the object \code{mHMM_gamma}.
#'
#' @export


plot.mHMM_gamma <- function(x, subj_nr = NULL, cex = 0.8, col, hide, ...){
  if (!requireNamespace("alluvial", quietly = TRUE)) {
    stop("Package \"alluvial\" needed for this function to work. Please install it.",
         call. = FALSE)
  }
  if (!requireNamespace("grDevices", quietly = TRUE)) {
    stop("Package \"grDevices\" needed for this function to work. Please install it.",
         call. = FALSE)
  }
  if (!is.mHMM_gamma(x)){
    stop("The input object x should be from the class mHMM_gamma, obtained with the function obtain_gamma.")
  }
  if (is.list(x)){
    if (is.null(subj_nr)){
      stop("When the input object x represents the subject specific transition
           probability matrices, the subject for which the probabilities should
           be plotted needs to be specified with the input variable -subj_nr-.")
    }
    m <- dim(x[[subj_nr]])[1]
    From <- paste("State", rep(1:m, each = m))
    To <-  paste("State", rep(1:m, m))
    trans <- as.vector(t(x[[subj_nr]]))
    foo <- data.frame(From, To, trans)
    if(missing(col)){
      col <- c(rep(grDevices::rainbow(m), eac = m))
    }
    if (missing(hide)){
      hide <- foo$trans == 0
    }
    alluvial::alluvial(foo[,1:2], freq=foo$trans,
                       cex = cex,
                       col = col,
                       hide = hide, ...)
  } else {
  m <- dim(x)[1]
  From <- paste("State", rep(1:m, each = m))
  To <-  paste("State", rep(1:m, m))
  trans <- as.vector(t(x))
  foo <- data.frame(From, To, trans)
  if(missing(col)){
    col <- c(rep(grDevices::rainbow(m), eac = m))
  }
  if (missing(hide)){
    hide <- foo$trans == 0
  }
  alluvial::alluvial(foo[,1:2], freq=foo$trans,
                     cex = cex,
                     col = col,
                     hide =  hide, ...)
  }
}


