#' Plotting the transition proabilities gamma for a fitted multilevel HMM
#'
#' \code{plot.mHMM_gamma} plots the tranisitoin probability matrix for a fitted
#' multilevel hidden markov model, by means of an alluvial plot (also known as
#' sankey diagram or riverplot) using the R package \code{alluvial}. The plotted
#' transition probability matrix either represents the probabilities at the
#' group level, i.e., representing the average transition probability matrix
#' over all subjects, or at the subject level. In case of the latter, the user
#' has to specify for which subject the transition probability matrix should be
#' plotted.
#'
#' @param object An object of class \code{mHMM_gamma}, generated by the function
#'   \code{\link{obtain_gamma}}.
#' @param subj_nr An integer specifying for which specific subject the
#'   transition probability matrix should be plotted. Only required if the input
#'   object represents the subject specific transition probability matrices.
#'
#' @return \code{plot.mHMM_gamma} returns a plot of the transition probability
#'   matrix. Depending on whether the input object represents the transiton
#'   probabilities at the group level or the subject specific transition
#'   probability matrices, the returned plot represents either the group
#'   transition probality matrix, or the transition probability matrix for a
#'   given subject, specified by \code{subject_nr}.
#'
#' @seealso \code{\link{mHMM_mnl}} for fitting the multilevel hidden Markov
#'   model, creating the object \code{mHMM}, and \code{\link{obtain_gamma}} to
#'   obtain the the transition proabilities gamma for a fitted multilevel HMM,
#'   creating the object \code{mHMM_gamma}.
#'
#' @export


plot.mHMM_gamma <- function(object, subj_nr = NULL){
  if (!requireNamespace("alluvial", quietly = TRUE)) {
    stop("Package \"alluvial\" needed for this function to work. Please install it.",
         call. = FALSE)
  }
  if (!is.mHMM_gamma(object)){
    stop("The input object used should be from the class mHMM_gamma, obtained by using the function obtain_gamma.")
  }
  if (is.list(object)){
    if (is.null(subj_nr)){
      stop("When the used input object represents the subject specific transition
           probability matrices, the subject for which the probabilities should
           be plotted needs to be specified with the input variable -subj_nr-.")
    }
    m <- dim(object[[subj_nr]])[1]
    From <- paste("State", rep(1:m, each = m))
    To <-  paste("State", rep(1:m, m))
    trans <- as.vector(t(object[[subj_nr]]))
    foo <- data.frame(From, To, trans)
    cols <- rainbow(m)
    alluvial::alluvial(foo[,1:2], freq=foo$trans,
                       cex = .8,
                       col = c(rep(cols, eac = m)),
                       hide = foo$trans == 0)
  } else {
  m <- dim(object)[1]
  From <- paste("State", rep(1:m, each = m))
  To <-  paste("State", rep(1:m, m))
  trans <- as.vector(t(object))
  foo <- data.frame(From, To, trans)
  cols <- rainbow(m)
  alluvial::alluvial(foo[,1:2], freq=foo$trans,
                     cex = .8,
                     col = c(rep(cols, eac = m)),
                     hide = foo$trans == 0)
  }
}


