#' Plotting the predicted transition/emission probabilities given certain values of covariates
#'
#' @param object Object of class \code{mHMM}, generated by the function
#'   \code{\link{mHMM}}.
#' @param component String specifying if the plot should be made for the
#'    transition probability matrix gamma (\code{component = "gamma"}) or
#'    for the emission distribution probabilities (\code{component = "emiss"}).
#' @param cov Integer that specifies which covariate to use for plotting when
#'    there are multiple covariates available. The default value is 1, which
#'    indicates the first covariate in the list of covariates.
#' @param dep Integer specifying for which dependent variable the predicted
#'    emission probabilities should be plotted.
#' @param col Vector of colors for the plots. If one is plotting the predicted
#'    transition probabilities, the vector has length \code{m} (i.e., number of
#'    hidden states). If one is plotting the predicted emission probabilities,
#'    the vector has length \code{q_emiss[k]} (i.e., the number of outcome
#'    categories for the dependent variable \code{k}).
#'    If not specified, colors will be assigned automatically.
#' @param cat_lab Optional vector of strings when plotting the predicted
#'    emission probabilities, denoting the labels of the categorical outcome values.
#'    Automatically generated when not provided.
#' @param dep_lab Optional string when plotting the predicted the emission
#'    probabilities with length 1, denoting the label for the dependent variable
#'    plotted. Automatically obtained from the input object when not specified.
#' @param cov_lab Optional string denoting the label for the covariate variable
#'    plotted. Automatically generated when not provided.
#' @param ... Other parameters passed down to \code{plot_pred()}.
#'
#' @export

plot_pred <- function(object, component = "gamma", cov = 1, dep = 1, col, cat_lab, dep_lab, cov_lab, ...) {
  if (!is.mHMM(object)){
    stop("The input object should be from the class mHMM, obtained with the function mHMM.")
  }
  if (component != "gamma" & component != "emiss"){
    stop("The input specified under component should be a string, restrectid to state either gamma or emiss.")
  }
  if (is.null(object$input$covar_type[[1]]) & is.null(object$input$covar_type[[2]])){
    stop("A covariate is required for predicting either transition or emission probabilities given the covariate values.")
  }
  input   <- object$input
  n_subj  <- input$n_subj
  dep_labels <- input$dep_labels
  burn_in <- input$burn_in
  J       <- input$J
  m       <- input$m
  q_emiss <- input$q_emiss
  n_dep   <- input$n_dep

  if (missing(cov_lab)) cov_lab <- paste0("covariate", cov)

  # common theme
  common_theme <- ggplot2::theme_bw() +
    ggplot2::theme(legend.position = "bottom")

  # if plotting gamma
  if(component == "gamma"){
    covar_gamma <- input$covariate[[1]][,cov +1]
    covar_type_gamma <- input$covar_type[[1]][cov]
    if (missing(col)){
      col <- scales::hue_pal()(m)
    } else {col <- col}
    # prepare subject df
    gg_subj <- obtain_gamma(object, level = "subject", burn_in = burn_in) |>
      purrr::reduce(rbind) |>
      tibble::as_tibble(rownames="From_state") |>
      dplyr::mutate(subject = rep(1:n_subj, each = m),
                    covariate = rep(covar_gamma, each = m)) |>
      tidyr::pivot_longer(cols=!c(subject, covariate, From_state),
                          names_to = "To_state", values_to="prob") |>
      dplyr::mutate(dplyr::across(c(To_state, From_state), stringr::str_replace,
                                  "To state|From state", "State"))

    # prepare emiss predicted value df
    preds <- pred_prob(object, cov = cov) |>
      tidyr::pivot_longer(!c(From_state, covariate), names_to = "To_state",
                          values_to = "prob") |>
      dplyr::mutate(dplyr::across(To_state, stringr::str_replace,
                                  "To_state_", "State "))

    if(covar_type_gamma == "continuous") {
      plot <- ggplot2::ggplot(data = gg_subj, ggplot2::aes(
        x = covariate, y = prob, color = To_state)) +
        ggplot2::geom_point(alpha = 0.6, size = 0.7) +
        ggplot2::geom_line(data = preds) +
        ggplot2::scale_color_manual(values = col) +
        ggplot2::labs(x = cov_lab, y = "Transition probability",
                      title = paste("Predicted transition probability"),
                      subtitle = paste("Given", cov_lab),
                      color = "To state") +
        ggplot2::ylim(0,1) +
        ggplot2::facet_grid(~From_state, labeller = ggplot2::as_labeller(
          function(string, prefix = "From") paste(prefix, string))) +
        common_theme

    } else if(covar_type_gamma == "dichotomous") {
      plot <- ggplot2::ggplot(data = gg_subj, ggplot2::aes(
        x = factor(covariate), y = prob, color = To_state)) +
        ggplot2::geom_point(alpha = 0.6, size = 0.7) +
        ggplot2::geom_boxplot(data = preds, width = 0.7, size = 0.5, outlier.shape = NA) +
        ggplot2::scale_color_manual(values = col) +
        ggplot2::labs(x = cov_lab, y = "Transition probability",
                      title = paste("Predicted transition probability"),
                      subtitle = paste("Given", cov_lab),
                      color = "To state") +
        ggplot2::ylim(0,1) +
        ggplot2::facet_grid(~From_state, labeller = ggplot2::as_labeller(
          function(string, prefix = "From") paste(prefix, string))) +
        common_theme
    }
  }

  # if plotting emiss
  else if(component == "emiss"){
    covar_emiss <- input$covariate[[2]][,cov +1] # given that all DVs share the same covariates
    covar_type_emiss <- input$covar_type[[2]][cov] # given that all DVs share the same covariates
    if (missing(cat_lab)){
      cat_lab <- paste("Category", 1:q_emiss[dep])
    }
    if (missing(dep_lab)){
      dep_lab <- input$dep_labels[dep]
    }
    if (missing(col)){
      col <- scales::hue_pal()(q_emiss[dep])
    } else {col <- col}
    # prepare subject df
    gg_subj <- obtain_emiss(object, level = "subject", burn_in = burn_in)[[dep]] |>
      purrr::reduce(rbind) |>
      tibble::as_tibble(rownames="State") |>
      dplyr::mutate(subject = rep(1:n_subj, each = m),
                    covariate = rep(covar_emiss, each = m)) |>
      tidyr::pivot_longer(cols=!c(subject, covariate, State),
                          names_to = "Category", values_to="prob")

    # prepare emiss predicted values
    preds <- purrr::quietly(pred_prob)(object, component = "emiss",
                                       cov = cov, dep = dep)$result |>
      tidyr::pivot_longer(!c(State, covariate), names_to = "Category",
                          values_to = "prob")
    if(covar_type_emiss == "continuous"){
      plot <- ggplot2::ggplot(data = gg_subj, ggplot2::aes(
        x = covariate, y = prob, color = Category)) +
        ggplot2::geom_point(alpha = 0.6, size = 0.7) +
        ggplot2::geom_line(data = preds) +
        ggplot2::scale_color_manual(values = col, labels = cat_lab) +
        ggplot2::labs(x = cov_lab, y = "Emission probability",
                      title = paste("Predicted emission probability of", dep_lab),
                      subtitle = paste("Given", cov_lab)) +
        ggplot2::ylim(0,1) +
        ggplot2::facet_grid(~State) +
        common_theme

    } else if(covar_type_emiss == "dichotomous") {
      plot <- ggplot2::ggplot(data = gg_subj, ggplot2::aes(
        x = factor(covariate), y = prob, color = Category)) +
        ggplot2::geom_point(alpha = 0.6, size = 0.7) +
        ggplot2::geom_boxplot(data = preds, width = 0.7, size = 0.5, outlier.shape = NA) +
        ggplot2::scale_color_manual(values = col, labels = cat_lab) +
        ggplot2::labs(x = cov_lab, y = "Emission probability",
                      title = paste("Predicted emission probability of", dep_lab),
                      subtitle = paste("Given", cov_lab)) +
        ggplot2::ylim(0,1) +
        ggplot2::facet_grid(~State) +
        common_theme
    }
  }
  return(plot)
}

utils::globalVariables(c("subject", "prob", "Category", "covariate", "From_state"))
