# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @keywords internal
cat_mult_fw_cpp <- function(allprobs, gamma, m, n, delta) {
    .Call(`_mHMMbayes_cat_mult_fw_cpp`, allprobs, gamma, m, n, delta)
}

