#' Plotting the traceplots of chains
#'
#' @param L a list of objects of class \code{mHMM} generated by the \code{\link{mHMM}} function.
#'

traceplot.mHMM <- function(L, component = "gamma", dep = 1, col, cat_lab,
                      dep_lab, burn_in, ...){
  if(!any(sapply(L, is.mHMM))){
    stop("Every input object of list L should be from the class mHMM, obtained with the function mHMM.")
  }
  if (component != "gamma" & component != "emiss"){
    stop("The input specified under component should be a string, restrectid to state either gamma or emiss.")
  }
  if (missing(burn_in)){
    burn_in <- L[[1]]$input$burn_in
  }
  J       <- L[[1]]$input$J
  if (burn_in >= (J-1)){
    stop(paste("The specified burn in period should be at least 2 points smaller
               compared to the number of iterations J, J =", J))
  }

  old_par <- graphics::par(no.readonly =TRUE)
  on.exit(graphics::par(old_par))
  m       <- L[[1]]$input$m
  q_emiss <- L[[1]]$input$q_emiss
  n_dep   <- L[[1]]$input$n_dep
  nchain <- length(L)

  # if plotting gamma
  if(component == "gamma"){
    # when ggplot2 & dplyr are available
    if(nzchar(system.file(package = "ggplot2")) && nzchar(system.file(package = "dplyr"))){

      # extract gamma matrices
      object <- purrr::map_dfr(1:length(L), ~ {
        L[[.x]]["gamma_prob_bar"]%>% as.data.frame() %>% dplyr::rename_with(~sub(".*bar.", "", .x)) %>%
          dplyr::mutate(iteration = dplyr::row_number()) %>% dplyr::slice(burn_in:J)
      } ,
      .id="chain") %>% tidyr::pivot_longer(!c(chain, iteration), names_to = "states", values_to = "value")

      # create traceplots
      if (nchain <= 1) {
        f <- ggplot2::ggplot(object, ggplot2::aes(x = iteration, y = value))
      } else {
        f <- ggplot2::ggplot(object, ggplot2::aes(x = iteration, y = value, colour = as.factor(chain)))
      }
      f <- f + ggplot2::geom_line(alpha=0.7) +
        ggplot2::scale_colour_discrete(name="Chain") +
        ggplot2::facet_wrap(~ states, ncol=1, scales="free")+
        ggplot2::labs(title = "transition probabilities", y = "")

      # when ggplot2 is not available, use baseR
    } else {

      if (missing(col)){
        state_col <- grDevices::rainbow(m)
      } else {
        state_col <- col
      }
      # specify layout
      graphics::par(mfrow = c(2, ceiling(m/2)), mar = c(4,2,3,1) + 0.1, mgp = c(2,1,0))

      for(i in 1:m){
        for(j in 1:m){
          graphics::plot.default(x = 1, xlim = c(burn_in, J), type = "n", cex = .8,
                                 ylab = "transition probability", xlab = "iteration")
          for(k in 1:nchain){
          print(m * (i-1) + j)
          lines(x = burn_in:J, y = L[[k]]$gamma_prob_bar[burn_in:J, m * (i-1) + j],
               ylab = "transition probability",
               xlab = "iteration", col = state_col[k])
          }
          graphics::title(main = paste("From state", i, "to State", j))
          graphics::legend("topright", col = state_col, legend = paste("Chain", 1:nchain),
                           bty = 'n', lty = 1, lwd = 2, cex = .8)
        }
      }

    }

    }
    # if plotting emiss
  } else if (component == "emiss"){
    if (missing(cat_lab)){
      cat_lab <- paste("Category", 1:L[[1]]$input$q_emiss[dep])
    }
    if (missing(dep_lab)){
      dep_lab <- L[[1]]$input$dep_labels[dep]
    }
    # if ggplot2 and dplyr are available
    if(nzchar(system.file(package = "ggplot2")) && nzchar(system.file(package = "dplyr"))){

      # extract emission prob matrices
      object <- purrr::map_dfr(1:length(L), ~ {
        L[[.x]]$emiss_prob_bar[[dep]] %>% as.data.frame() %>% dplyr::mutate(iteration = dplyr::row_number()) %>% dplyr::slice(burn_in:J)
      } ,
      .id="chain") %>% tidyr::pivot_longer(!c(chain, iteration), names_to = "states", values_to = "value")
      # create traceplots
      if (nchain <= 1) {
        f <- ggplot2::ggplot(object, ggplot2::aes(x = iteration, y = value))
      } else {
        f <- ggplot2::ggplot(object, ggplot2::aes(x = iteration, y = value, colour = as.factor(chain)))
      }
      f <- f + ggplot2::geom_line(alpha=0.7) +
        ggplot2::scale_colour_discrete(name="Chain") +
        ggplot2::facet_wrap(~ states, ncol=1, scales="free") +
        ggplot2::labs(title = dep_lab, y = "")

      # if ggplot2 is not available, use baseR
    } else {

    }
  }
  return(f)
}
